Repository AY2021S1-CS2103T-T12-3/tp, pull requests merged in 2020-10, with the labels that each got.

#125 Zijian/change email to description
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Email.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidTaskAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTaskAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DescriptionTest.java
  src/test/java/seedu/address/model/task/EmailTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#135 Limit task to 3 different types using enum
  src/main/java/seedu/address/model/task/Type.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidTaskAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidTaskAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalTaskAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/TypeTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: severity.High

#134 Zijian/Reimplement Find function
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TitleContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlanusParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/TaskContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
Labels: priority.Medium

#142 Gangwei/Update taskcard ui
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: priority.High

#130 Beining/done command
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/State.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High

#165 Beining/done command fix
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializablePlanusTest/typicalTaskPlanus.json
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.Medium

#161 Zijian/implement find for status
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/task/DateTime.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/Title.java
  src/main/java/seedu/address/model/task/Type.java
  src/main/java/seedu/address/storage/JsonPlanusStorage.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlanusParserTest.java
  src/test/java/seedu/address/model/task/TaskContainsKeywordsPredicateTest.java
Labels: priority.Medium, type.Feature.To-Do-List

#169 Refactor datetime class
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planus.java
  src/main/java/seedu/address/model/task/DateTime.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: priority.High, type.Task

#166 add varargs function for delete command and update testcase
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planus.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlanusParserTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Labels: priority.Medium

#177 Fix wrong assertions
  src/main/java/seedu/address/model/lesson/Date.java
  src/main/java/seedu/address/model/lesson/Time.java
  src/main/java/seedu/address/model/task/DateTime.java
Labels: type.Bug

#183 Zijian/Store lesson in Json
  src/main/java/seedu/address/logic/commands/LessonCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planus.java
  src/main/java/seedu/address/model/ReadOnlyPlanus.java
  src/main/java/seedu/address/model/lesson/UniqueLessonList.java
  src/main/java/seedu/address/model/lesson/exceptions/DuplicateLessonException.java
  src/main/java/seedu/address/model/lesson/exceptions/LessonNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonSerializablePlanus.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/PlanusTest.java
Labels: priority.Medium, type.Feature.NUS-Mod-Calendar

#185 Marcus/Input validation for date and time in lesson command
  src/main/java/seedu/address/logic/parser/LessonCommandParser.java
  src/main/java/seedu/address/model/lesson/Date.java
  src/main/java/seedu/address/model/lesson/Time.java
Labels: priority.High

#188 Gangwei/add lesson list ui
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/LessonListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LessonListCard.fxml
  src/main/resources/view/LessonListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#186 [DO NOT MERGE] Improve UG
  docs/UserGuide.md
Labels: type.Documentation

#196 Zijian/Implement lesson commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/ListLessonCommand.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planus.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/UniqueLessonList.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/LessonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: priority.High, type.Feature.Find-Command

#206 Gangwei/improve ui
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/card/DeadlineCard.java
  src/main/java/seedu/address/ui/card/EventCard.java
  src/main/java/seedu/address/ui/card/LessonCard.java
  src/main/resources/view/DataAnalysisPanel.fxml
  src/main/resources/view/DeadlineCard.fxml
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/LessonCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: severity.High, type.Bug

#208 Zijian/change command word
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/main/java/seedu/address/model/StatisticsData.java
  src/main/java/seedu/address/storage/Statistics.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlanusParserTest.java
Labels: priority.Medium, type.Enhancement

#211 fix bugs in edit task command
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
Labels: type.Bug

#210 Gangwei/improve ui
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planus.java
  src/main/java/seedu/address/ui/DataAnalysisPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/DataAnalysisPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatsSummaryPanel.fxml
Labels: priority.High, severity.High, type.Bug

#212 fix delete lesson bug
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/main/java/seedu/address/model/Planus.java
Labels: severity.High, type.Bug
