Repository AY2021S1-CS2103T-T12-3/tp, pull requests merged in 2020-11, with the labels that each got.

#247 Zijian/fix index error msg
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/FindLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/LessonCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlanusParserTest.java
Labels: severity.Low, type.Bug

#248 fix deadline square bracket
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/task/deadline/Deadline.java
  src/main/java/seedu/address/model/task/event/Event.java
Labels: type.Bug, type.Documentation

#209 Marcus/time
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/LessonCommand.java
  src/main/java/seedu/address/logic/parser/LessonCommandParser.java
  src/main/java/seedu/address/model/Planus.java
  src/main/java/seedu/address/model/StatisticsData.java
  src/main/java/seedu/address/model/TimeSlot.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/task/DateTime.java
  src/main/java/seedu/address/model/task/deadline/Deadline.java
  src/main/java/seedu/address/model/task/event/Event.java
  src/main/java/seedu/address/model/util/Overlap.java
Labels: priority.Medium, type.Enhancement

#200 Refactor help window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Medium, type.Enhancement

#250 Zijian/check invalid date
  src/main/java/seedu/address/commons/util/DateTimeUtil.java
  src/main/java/seedu/address/logic/parser/FindLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/LessonCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/LessonContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/lesson/Time.java
  src/main/java/seedu/address/model/task/DateTime.java
  src/main/java/seedu/address/model/task/TaskContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/deadline/DeadlineDateTime.java
  src/main/java/seedu/address/model/task/deadline/DoneDateTime.java
  src/main/java/seedu/address/model/task/event/EndDateTime.java
  src/main/java/seedu/address/model/task/event/StartDateTime.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeadlineTest.java
Labels: type.Bug

#260 zijian/update ppp
  docs/team/bobbyzhouzijian.md
Labels: type.Documentation

#267 Zijian/check overlap for edit AND code clean up
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/LessonCommand.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TimeSlot.java
  src/main/java/seedu/address/model/task/deadline/Duration.java
  src/main/java/seedu/address/model/util/Overlap.java
  src/main/java/seedu/address/storage/JsonAdaptedDeadline.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/LessonCommandTest.java
Labels: priority.High, type.Enhancement

#246 update Appendix:Requirements section of DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#270 Zijian/more refactoring
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/FindLessonCommand.java
  src/main/java/seedu/address/logic/commands/FindTaskCommand.java
  src/main/java/seedu/address/logic/commands/LessonCommand.java
  src/main/java/seedu/address/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLessonCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/LessonCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/PlanusParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditLessonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LessonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/PlanusParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium, type.Enhancement

#273 Zijian/update sample data
  src/main/java/seedu/address/logic/commands/CalendarCommand.java
  src/main/java/seedu/address/logic/commands/DeadlineCommand.java
  src/main/java/seedu/address/logic/commands/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/commands/LessonCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Enhancement
